.\"
.\" Define V font for inline verbatim, using C font in formats
.\" that render this, and otherwise B font.
.ie "\f[CB]x\f[]"x" \{\
. ftr V B
. ftr VI BI
. ftr VB B
. ftr VBI BI
.\}
.el \{\
. ftr V CR
. ftr VI CI
. ftr VB CB
. ftr VBI CBI
.\}
.TH "CINFO" "1" "" "Version-VERSION" "cinfo Manual"
.hy
.SH NAME
.PP
cinfo - system information utility
.SH SYNOPSIS
.PP
\f[B]cinfo\f[R] [\f[B]-a\f[R]] [\f[B]-c\f[R]] [\f[B]-i\f[R]]
.SH DESCRIPTION
.PP
\f[B]cinfo\f[R] is a fast and minimal system information tool for
linux-based operating systems
.SH OPTIONS
.PP
Without given setting, start colored verion.
.TP
\f[B]-a\f[R]
Start plain ascii version.
.TP
\f[B]-c\f[R]
Clear cached files.
.TP
\f[B]-i\f[R]
Shows informations about execution times of the individual functions for
optimization and the version
.SH CUSTOMIZATION
.PP
\f[B]cinfo\f[R] can be customized by creating/editing a custom config.h
and (re-)compiling the source code.
.TP
\f[B]\f[BI]PKGS*\f[B]\f[R]
Values to configure package manager counting.
.TP
\f[B]\f[BI]INFO*\f[B]\f[R]
Values to configure information in general.
.TP
\f[B]\f[BI]SHELL*\f[B]\f[R]
Values to configure shell information.
.TP
\f[B]\f[BI]CPU*\f[B]\f[R]
Values to configure cpu information.
.TP
\f[B]\f[BI]MEMORY*\f[B]\f[R]
Values to configure memory information.
.PP
\f[B]MEMORY_METHOD\f[R]
.PP
.TS
tab(@);
cw(4.9n) lw(38.5n) lw(26.6n).
T{
Value
T}@T{
Calculation
T}@T{
Comparable
T}
_
T{
0
T}@T{
total - available
T}@T{
htop = 3.1.0, btop, polybar
T}
T{
1
T}@T{
total + shared - free - buffer - cached
T}@T{
htop < 3.1.0, neofetch
T}
T{
2
T}@T{
total - free - buffer - cached
T}@T{
htop > 3.1.0, free
T}
.TE
.PP
\f[B]MEMORY_UNIT\f[R]
.PP
.TS
tab(@);
l l l.
T{
Value
T}@T{
Condition
T}@T{
Description
T}
_
T{
auto
T}@T{
total => 1024 MiB
T}@T{
Shows result in Gibibyte
T}
T{
T}@T{
total < 1024 MiB
T}@T{
Shows result in Mebibyte
T}
T{
GiB
T}@T{
T}@T{
Shows result in Gibibyte
T}
T{
MiB
T}@T{
T}@T{
Shows result in Mebibyte
T}
.TE
.TP
\f[B]\f[BI]COLOR*\f[B]\f[R]
Values to configure color table.
.TP
\f[B]\f[BI]ASCII*\f[B]\f[R]
Values to configure ascii table.
.TP
\f[B]\f[BI]LABEL*\f[B]\f[R]
Values to configure labels for ascii and color table.
.TP
\f[B]\f[BI]CACHE*\f[B]\f[R]
Values to configure the cache paths.
.SH EXAMPLES
.PP
\f[B]cinfo\f[R]
.PD 0
.P
.PD
\f[B]cinfo\f[R] -a
.PD 0
.P
.PD
\f[B]cinfo\f[R] -c
.PD 0
.P
.PD
\f[B]cinfo\f[R] -i
.SH BUGS
.PP
See GitHub Issues: \f[I]https://github.com/mrdotx/cinfo/issues\f[R]
.SH AUTHORS
.PP
\f[B]cinfo\f[R] was written by mrdotx <\f[I]klassiker\[at]gmx.de\f[R]>
.SH SEE ALSO
.PP
\f[B]htop\f[R](1), \f[B]free\f[R](1), \f[B]neofetch\f[R](1),
\f[B]polybar\f[R](1)
.SH LICENSE
.PP
See the \f[I]LICENSE.md\f[R] file for the terms of redistribution.
